yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = "core.views.page_not_found"
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self) -> str:
        return self.title


class Post(models.Model):
    text = models.TextField(
        verbose_name='text',
        help_text='Текст нового поста'

    )
    pub_date = models.DateTimeField(auto_now_add=True)
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        related_name='posts',
        blank=True,
        null=True,
        verbose_name='Группа',
        help_text='Группа к которой будет относиться пост'

    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )

    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    def __str__(self):
        # выводим текст поста
        return self.text[:15]

    class Meta:
        ordering = ['-pub_date']


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.SET_NULL,
        related_name='comments',
        blank=True,
        null=True,
        verbose_name='Пост',
        help_text='Пост, к которому будет оставлен комментарий'
    )

    author = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        related_name='comments',
        blank=True,
        null=True,
        verbose_name='Автор комментария',
    )

    text = models.TextField(
        null=True,
        max_length=400,
        verbose_name='Текст комментария',
        help_text='Текст нового комментария',
    )

    created = models.DateTimeField(
        auto_now_add=True, verbose_name='Дата публикации комментария'
    )

    def __str__(self):
        # выводим текст поста
        return self.text


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        blank=True,
        null=True,
        verbose_name='Имя подписчика',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        blank=True,
        null=True,
        verbose_name='Имя автора',
    )

yatube/posts/forms.py
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('group', 'text', 'image')
        labels = {
            'image': ('author'),
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text', )

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from .forms import PostForm, CommentForm
from .models import Post, Group, User, Follow

pagi = 10


def index(request):
    """Главная страница."""
    post_list = Post.objects.all().order_by('-pub_date')
    paginator = Paginator(post_list, pagi)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    """Посты в группе."""
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()
    paginator = Paginator(posts, pagi)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    """Посты пользователя."""
    author = get_object_or_404(User, username=username)
    posts = author.posts.all()
    posts_count = author.posts.count()
    paginator = Paginator(posts, pagi)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    following = (request.user.is_authenticated
                 and Follow.objects.filter(
                     user=request.user,
                     author=author).exists()
                 )
    context = {
        'author': author,
        'posts_count': posts_count,
        'page_obj': page_obj,
        'following': following,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    """Открыть пост."""
    post = get_object_or_404(Post, pk=post_id)
    group = post.group
    author = post.author
    posts_count = author.posts.count()
    comments = post.comments.all()
    form = CommentForm(request.POST or None)
    context = {
        'post': post,
        'comments': comments,
        'group': group,
        'form': form,
        'posts_count': posts_count,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    """Создание нового поста."""
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,)

    if form.is_valid():
        form.instance.author = request.user
        form.save()
        return redirect('posts:profile', username=request.user.username)

    context = {
        'is_edit': False,
        'title': 'Новый пост',
        'groups': Group.objects.all(),
        'form': form,
    }

    return render(request, 'posts/create_post.html', context)


@login_required
def post_edit(request, post_id):
    """Редактирование поста."""
    post = get_object_or_404(Post, id=post_id)
    # Если текущий пользователь не автор - ничего не делается
    if post.author != request.user:
        return redirect('posts:post_detail', post.id)

    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )

    if request.method == 'POST' and form.is_valid():
        form.save()
        return redirect('posts:post_detail', post.id)

    context = {
        'is_edit': True,
        'title': 'Редактирование поста',
        'groups': Group.objects.all(),
        'post_id': post.id,
        'form': form,
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    posts = Post.objects.filter(
        author__following__user=request.user)
    paginator = Paginator(posts, pagi)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    context = {
        'posts': posts,
        'page_obj': page_obj,
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    user = request.user
    author = get_object_or_404(User, username=username)
    if user != author:
        Follow.objects.get_or_create(
            user=user,
            author=author,
        )
    return redirect('posts:follow_index')


@login_required
def profile_unfollow(request, username):
    get_object_or_404(
        Follow, user=request.user, author__username=username).delete()
    return redirect('posts:profile', username=username)

yatube/templates/posts/comments.html
<!-- Форма добавления комментария -->
{% load user_filters %}

{% if user.is_authenticated %}
  <div class="card my-4">
    <h5 class="card-header">Добавить комментарий:</h5>
    <div class="card-body">
      <form method="post" action="{% url 'posts:add_comment' post.id %}">
        {% csrf_token %}      
        <div class="form-group mb-2">
          {{ form.text|addclass:"form-control" }}
        </div>
        <button type="submit" class="btn btn-primary">Отправить</button>
      </form>
    </div>
  </div>
{% endif %}

{% for comment in comments %}
  <div class="media mb-4">
    <div class="media-body">
      <h5 class="mt-0">
        <a href="{% url 'posts:profile' comment.author.username %}">
          {{ comment.author.username }}
        </a>
      </h5>
        <p>
         {{ comment.text }}
        </p>
      </div>
    </div>
{% endfor %}

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% block title %}
    {{ title }}
{% endblock title %}
{% load thumbnail %}

{% block content %}
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            {{ title }}
          </div>
          {% load user_filters %}
          <div class="card-body">
            <form method="post" enctype="multipart/form-data">
              {% csrf_token %}
              <div class="form-group row my-3 p-3">
                <label for="id_text">
                  Текст поста
                  <span class="required text-danger">*</span>
                </label>
                {{ form.text|addclass:'form-control' }}
                <small id="id_text-help" class="form-text text-muted">
                  Текст нового поста
                </small>
              </div>
              <div class="form-group row my-3 p-3">
                <label for="id_group">
                  Группа
                </label>
                {{ form.group|addclass:'form-control' }}
                <small id="id_group-help" class="form-text text-muted">
                  Группа, к которой будет относиться пост
                </label>
                {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
                  <img class="card-img my-2" src="{{ im.url }}">
                {% endthumbnail %}
                </small>
              </div>
              <div class="d-flex justify-content-end">
                    {% if is_edit %}
                        <button type="submit" class="btn btn-primary" value="{% url 'posts:post_edit' post_id %}">
                            Обновить
                        </button>
                    {% else %}
                         <button type="submit" class="btn btn-primary" value="{% url 'posts:post_create' %}">
                            Добавить
                        </button>
                    {% endif %}
                  </ul>
                  {{ form.image|addclass:'form-control' }}
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
{% endblock content %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% block title %}Вы подписаны на авторов{% endblock %}
{% block header %} Посты авторов, на которых вы подписаны {% endblock %}
{% load cache %}
{% cache 20 index_page %}
  {% block content %}
  {% include 'posts/includes/switcher.html' %}
  {% load thumbnail %}
    {% for post in posts %}
      <ul>
        <li>
          Автор: 
          <a href="{% url 'posts:profile' post.author.username %}"> {{ post.author.username}}</a>
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      {{ post.text|linebreaks }}
      {% if post.group.slug %}
      Все записи группы:
        <a href="{% url 'posts:group_list' post.group.slug %}"> {{post.group.title}} </a> 
      {% endif %}
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
  {% endblock %}
{% endcache %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}{{ group }}{% endblock title %}
{% block content %}
      <!-- класс py-5 создает отступы сверху и снизу блока -->
        <h1>{{ group.title }}</h1>
        <p>
          {{ group.description }}
        </p>
        {% for post in page_obj %}
          <article>
            {% include './post.html' %}     
          </article>
          <br>
            <a href="{% url 'posts:post_detail' post.pk %}">Подробная информация</a>
          <br>
            <a href="{% url 'posts:profile' post.author %}">Все посты пользователя : {{ post.author.get_full_name }}</a>
          <br>
          {% if not forloop.last %}<hr>{% endif %}
        {% endfor %}
        {% include 'posts/includes/paginator.html'  %}
{% endblock content %}

      

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load static %}
{% load thumbnail %}
{% block title %} Последние обновления на сайте {% endblock title %}
{% load cache %}
{% block content %}
{% include 'posts/includes/switcher.html' %}
{% cache 20 index_page page_obj.number %}
<h1> Последние обновления на сайте </h1>
<article>
{% for post in page_obj %}
  <ul>
    <li>
      Автор: {{ post.author.get_full_name }}
    </li>
    <li>
      Дата публикации: {{ post.pub_date|date:'d E Y' }}
    </li>
  </ul>      
  <p>
  {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img my-2" src="{{ im.url }}">
  {% endthumbnail %}
    {{ post.text }}
  </p>
  <a href="{% url 'posts:post_detail' post.pk %}">Подробная информация</a>
  {% if post.group %}
  <br>
   <a href="{% url 'posts:group_list' post.group.slug %}">Все записи группы{{ group.description }}</a>
  <br>
  {% endif %}
  <hr>
{% endfor %}
{% include 'posts/includes/paginator.html' %} 
</article>
{% if not forloop.last %}<hr>{% endif %}
{%endcache%}
{%endblock%}

yatube/templates/posts/post.html
{% load thumbnail %}
<ul>
  <li>
    Автор: {{ post.author.get_full_name }}
  </li>
  <li>
    Дата публикации: {{ post.pub_date|date:"d E Y" }}
  </li>
</ul> 
<p>{{ post.text }}</p>
{% thumbnail post.image "960x339" crop="center" upscale=True as im %}
<img class="card-img my-2" src="{{ im.url }}">
{% endthumbnail %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{%block title %}
Пост {{ post.text }}
{%endblock%}
{% load thumbnail %}

{%block content%}
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Дата публикации: {{ post.pub_date|date:'d E Y' }}
        </li>
      </ul>
        {%if post.group %}
          <li class="list-group-item">
            Группа: {{group.title}}
            <br>
            <a href="{% url 'posts:group_list' post.group.slug %}">
              Все записи группы
            </a>
          </li>
        {% endif %}
        <li class="list-group-item">
          Автор: {{post.author.get_full_name}}
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Всего постов автора:  <span >{{posts_count}}</span>
        </li>
        <li class="list-group-item">
        <a href="{% url 'posts:profile' post.author %}">
          Все посты пользователя
        </a>
        <br><br>
         {%  if user.is_authenticated %}
            <a href="{% url 'posts:post_edit' post.id %}">
                Редактировать пост
            </a>
         {% endif %}
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
      <p>
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
        {{ post.text }}
      </p>
      {% include 'posts/comments.html' %}
    </article>
  </div>
{%endblock%}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{%block title %}Профайл пользователя {{User.username}}
{%endblock%}
{% load thumbnail %}
{%block content%}   
<div class="mb-5">
  <h1>Все посты пользователя {{ author.get_full_name }}</h1>
  <h3>Всего постов: {{ posts_count }}</h3>
  {% if following %}
    <a
      class="btn btn-lg btn-light"
      href="{% url 'posts:profile_unfollow' author.username %}" role="button"
    >
      Отписаться
    </a>
  {% else %}
    <a
      class="btn btn-lg btn-primary"
      href="{% url 'posts:profile_follow' author.username %}" role="button"
    >
      Подписаться
    </a>
   {% endif %}
</div>
    <article>
      {%for post in page_obj%}
        <ul>
          <li>
            Автор: {{post.author.get_full_name}}
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:'d E Y' }}
          </li>
        </ul>
        <p>
        {% thumbnail post.image "960x520" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
          {{ post.text }}
        </p>
        <a href="{% url 'posts:post_detail' post.pk %}">Подробная информация</a>
        <br>
          <a href="{% url 'posts:index' %}">Все посты пользователя: {{ post.author.get_full_name }}</a>
        <br>
        {% if not forloop.last %}<hr>{% endif %}
      {% endfor %}
    </article>
    {% include 'posts/includes/paginator.html'  %}
{%endblock%}